import { MigrationInterface, QueryRunner } from 'typeorm';

export class CrearEsquemaInicial1710000000000 implements MigrationInterface {
  name = 'CrearEsquemaInicial1710000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE usuarios (pk_usuario char(36) NOT NULL, nombre_usuario varchar(50) NOT NULL, nombre_completo varchar(120) NOT NULL, hash_contrasena varchar(255) NOT NULL, tipo_usuario enum ('AGENCIA','GRUPERO','BANQUERO') NOT NULL, activo tinyint NOT NULL DEFAULT 1, creado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, modificado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (pk_usuario), UNIQUE KEY uq_usuarios_nombre_usuario (nombre_usuario)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE gruperos (pk_grupero char(36) NOT NULL, fk_usuario char(36) NOT NULL, fk_banquero char(36) NOT NULL, cupo_animal decimal(12,2) NOT NULL DEFAULT 500, comision_porcentaje decimal(6,3) NOT NULL DEFAULT 3, activo tinyint NOT NULL DEFAULT 1, modificado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, fk_usuario_modificado char(36) NULL, PRIMARY KEY (pk_grupero), UNIQUE KEY uq_gruperos_usuario (fk_usuario), CONSTRAINT fk_gruperos_usuario FOREIGN KEY (fk_usuario) REFERENCES usuarios(pk_usuario), CONSTRAINT fk_gruperos_banquero FOREIGN KEY (fk_banquero) REFERENCES usuarios(pk_usuario)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE agencias (pk_agencia char(36) NOT NULL, codigo_agencia varchar(20) NOT NULL, nombre_agencia varchar(120) NOT NULL, comision_porcentaje decimal(6,3) NOT NULL DEFAULT 12, cupo_animal decimal(12,2) NOT NULL DEFAULT 100, jugada_minima decimal(12,2) NOT NULL DEFAULT 1, minutos_cierre smallint NOT NULL DEFAULT 5, serial_pc varchar(100) NULL, proximo_numero_ticket int NOT NULL DEFAULT 1, fk_usuario char(36) NOT NULL, fk_banquero char(36) NOT NULL, fk_grupero char(36) NULL, activa tinyint NOT NULL DEFAULT 1, creado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, modificado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, fk_usuario_modificado char(36) NULL, PRIMARY KEY (pk_agencia), UNIQUE KEY uq_agencias_codigo (codigo_agencia), CONSTRAINT fk_agencias_usuario FOREIGN KEY (fk_usuario) REFERENCES usuarios(pk_usuario), CONSTRAINT fk_agencias_banquero FOREIGN KEY (fk_banquero) REFERENCES usuarios(pk_usuario), CONSTRAINT fk_agencias_grupero FOREIGN KEY (fk_grupero) REFERENCES gruperos(pk_grupero)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE animales (pk_animal int NOT NULL AUTO_INCREMENT, codigo_animal varchar(2) NOT NULL, nombre varchar(60) NOT NULL, icono varchar(8) NOT NULL, activo tinyint NOT NULL DEFAULT 1, modificado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (pk_animal), UNIQUE KEY uq_animales_codigo (codigo_animal)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE sorteos (pk_sorteo int NOT NULL AUTO_INCREMENT, nombre varchar(50) NOT NULL, activo tinyint NOT NULL DEFAULT 1, modificado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (pk_sorteo), UNIQUE KEY uq_sorteos_nombre (nombre)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE horarios_sorteo (pk_horario_sorteo int NOT NULL AUTO_INCREMENT, fk_sorteo int NOT NULL, hora time NOT NULL, activo tinyint NOT NULL DEFAULT 1, modificado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (pk_horario_sorteo), UNIQUE KEY uq_horarios_sorteo_hora (fk_sorteo,hora), CONSTRAINT fk_horarios_sorteos FOREIGN KEY (fk_sorteo) REFERENCES sorteos(pk_sorteo)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE tickets (pk_ticket char(36) NOT NULL, serial varchar(24) NOT NULL, numero_ticket int NOT NULL, fecha_juego date NOT NULL, fk_agencia char(36) NOT NULL, estado enum ('ACTIVO','CANCELADO','PREMIADO','PAGADO') NOT NULL DEFAULT 'ACTIVO', total_jugado decimal(12,2) NOT NULL, total_premio decimal(12,2) NOT NULL DEFAULT 0, monto_pagado decimal(12,2) NOT NULL DEFAULT 0, creado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, modificado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, fk_usuario_modificado char(36) NOT NULL, PRIMARY KEY (pk_ticket), UNIQUE KEY uq_tickets_serial (serial), UNIQUE KEY uq_tickets_numero_por_agencia_dia (fk_agencia,numero_ticket,fecha_juego), CONSTRAINT fk_tickets_agencia FOREIGN KEY (fk_agencia) REFERENCES agencias(pk_agencia), CONSTRAINT fk_tickets_usuario_modificado FOREIGN KEY (fk_usuario_modificado) REFERENCES usuarios(pk_usuario)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE jugadas_ticket (pk_jugada_ticket char(36) NOT NULL, fk_ticket char(36) NOT NULL, fk_animal int NOT NULL, fk_horario_sorteo int NOT NULL, fecha_juego date NOT NULL, monto decimal(12,2) NOT NULL, estado enum ('ACTIVA','CANCELADA','PREMIADA','PAGADA') NOT NULL DEFAULT 'ACTIVA', modificado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, fk_usuario_modificado char(36) NOT NULL, PRIMARY KEY (pk_jugada_ticket), KEY ix_jugadas_cupo (fecha_juego,fk_horario_sorteo,fk_animal), CONSTRAINT fk_jugadas_ticket FOREIGN KEY (fk_ticket) REFERENCES tickets(pk_ticket), CONSTRAINT fk_jugadas_animal FOREIGN KEY (fk_animal) REFERENCES animales(pk_animal), CONSTRAINT fk_jugadas_horario FOREIGN KEY (fk_horario_sorteo) REFERENCES horarios_sorteo(pk_horario_sorteo), CONSTRAINT fk_jugadas_usuario_modificado FOREIGN KEY (fk_usuario_modificado) REFERENCES usuarios(pk_usuario)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE resultados (pk_resultado char(36) NOT NULL, fecha_juego date NOT NULL, fk_horario_sorteo int NOT NULL, fk_animal int NOT NULL, insertado_at datetime NOT NULL, modificado_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, fk_usuario_modificado char(36) NOT NULL, PRIMARY KEY (pk_resultado), UNIQUE KEY uq_resultados_horario_dia (fecha_juego,fk_horario_sorteo), CONSTRAINT fk_resultados_horario FOREIGN KEY (fk_horario_sorteo) REFERENCES horarios_sorteo(pk_horario_sorteo), CONSTRAINT fk_resultados_animal FOREIGN KEY (fk_animal) REFERENCES animales(pk_animal), CONSTRAINT fk_resultados_usuario_modificado FOREIGN KEY (fk_usuario_modificado) REFERENCES usuarios(pk_usuario)) ENGINE=InnoDB`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const tabla of ['resultados', 'jugadas_ticket', 'tickets', 'horarios_sorteo', 'sorteos', 'animales', 'agencias', 'gruperos', 'usuarios']) await queryRunner.query(`DROP TABLE ${tabla}`);
  }
}
