#!/bin/sh
set -eu

mysql -uroot -p"${MARIADB_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${MARIADB_MIGRACIONES_USUARIO}'@'%' IDENTIFIED BY '${MARIADB_MIGRACIONES_CONTRASENA}';
GRANT ALTER, CREATE, DROP, INDEX, REFERENCES, SELECT, INSERT, UPDATE, DELETE ON \`${MARIADB_DATABASE}\`.* TO '${MARIADB_MIGRACIONES_USUARIO}'@'%';
FLUSH PRIVILEGES;
SQL

