import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const recursos = {
  es: { translation: { entrar: 'Entrar', usuario: 'Usuario', contrasena: 'Contraseña', cerrar_sesion: 'Cerrar sesión', venta: 'Venta', animales: 'Animales', sorteos: 'Sorteos', monto: 'Monto', agregar: 'Agregar jugada', emitir: 'Emitir ticket', selecciona: 'Selecciona al menos un animal y un sorteo.', jugadas: 'Jugadas', total: 'Total', cupo: 'Cupo por animal', venta_exitosa: 'Ticket emitido', tema: 'Tema', claro: 'Claro', oscuro: 'Oscuro', idioma: 'Idioma', cancelar: 'Cancelar', ticket: 'Ticket', no_hay_jugadas: 'Aún no hay jugadas en el ticket.', acceso_agencia: 'Acceso de Agencia', iniciar_descripcion: 'Ingresa con tus credenciales para registrar ventas.', error_sesion: 'No fue posible iniciar sesión.', disponible: 'Disponible', salir: 'Salir', todos: 'Todos', filtrar_sorteos: 'Filtrar sorteos', proximo_cierre: 'Cierra {{hora}} · {{sorteo}}', sin_sorteos_disponibles: 'Sin sorteos disponibles', menu: 'Menú', navegacion_principal: 'Navegación principal', venta_animalitos: 'Venta de animalitos', resumen_ventas: 'Resumen de ventas', ver_resultados: 'Ver resultados', listado_tickets: 'Listado de tickets', sesion_vencida: 'Tu sesión venció', sesion_vencida_descripcion: 'Volverás al inicio de sesión en unos segundos. También puedes salir ahora.' } },
  it: { translation: { entrar: 'Accedi', usuario: 'Utente', contrasena: 'Password', cerrar_sesion: 'Esci', venta: 'Vendita', animales: 'Animali', sorteos: 'Estrazioni', monto: 'Importo', agregar: 'Aggiungi giocata', emitir: 'Emetti biglietto', selecciona: 'Seleziona almeno un animale e un’estrazione.', jugadas: 'Giocate', total: 'Totale', cupo: 'Limite per animale', venta_exitosa: 'Biglietto emesso', tema: 'Tema', claro: 'Chiaro', oscuro: 'Scuro', idioma: 'Lingua', cancelar: 'Annulla', ticket: 'Biglietto', no_hay_jugadas: 'Non ci sono ancora giocate nel biglietto.', acceso_agencia: 'Accesso Agenzia', iniciar_descripcion: 'Accedi per registrare le vendite.', error_sesion: 'Non è stato possibile accedere.', disponible: 'Disponibile', salir: 'Esci', todos: 'Tutti', filtrar_sorteos: 'Filtra estrazioni', proximo_cierre: 'Chiude alle {{hora}} · {{sorteo}}', sin_sorteos_disponibles: 'Nessuna estrazione disponibile', menu: 'Menu', navegacion_principal: 'Navigazione principale', venta_animalitos: 'Vendita di animaletti', resumen_ventas: 'Riepilogo vendite', ver_resultados: 'Vedi risultati', listado_tickets: 'Elenco biglietti', sesion_vencida: 'La sessione è scaduta', sesion_vencida_descripcion: 'Tornerai alla schermata di accesso tra pochi secondi. Puoi anche uscire subito.' } },
};

const idiomaGuardado = localStorage.getItem('ag_idioma');
void i18n.use(initReactI18next).init({ resources: recursos, lng: idiomaGuardado ?? 'es', fallbackLng: 'es', interpolation: { escapeValue: false } });
export default i18n;
