import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const traduccionesConsulta = {
  es: { fecha: 'Fecha', estado: 'Estado', cerrar: 'Cerrar', cargando: 'Cargando…', buscar: 'Buscar', ejemplo_temporal: 'Ejemplo temporal', consulta_error: 'No fue posible cargar la consulta.', sin_resultados: 'No hay resultados registrados para esta fecha.', sin_tickets: 'No hay tickets para este filtro.', desde: 'Desde', hasta: 'Hasta', total_vendido: 'Total vendido', total_premiado: 'Total premiado', porcentaje: 'Porcentaje', resto: 'Resto', estado_activo: 'Vendido', estado_cancelado: 'Anulado', estado_premiado: 'Premiado', estado_pagado: 'Pagado' },
  it: { fecha: 'Data', estado: 'Stato', cerrar: 'Chiudi', cargando: 'Caricamento…', buscar: 'Cerca', ejemplo_temporal: 'Esempio temporaneo', consulta_error: 'Non è stato possibile caricare la consultazione.', sin_resultados: 'Non ci sono risultati registrati per questa data.', sin_tickets: 'Non ci sono biglietti per questo filtro.', desde: 'Da', hasta: 'A', total_vendido: 'Totale venduto', total_premiado: 'Totale premi', porcentaje: 'Percentuale', resto: 'Resto', estado_activo: 'Venduto', estado_cancelado: 'Annullato', estado_premiado: 'Premiato', estado_pagado: 'Pagato' },
};

const recursos = {
  es: { translation: { entrar: 'Entrar', usuario: 'Usuario', contrasena: 'Contraseña', cerrar_sesion: 'Cerrar sesión', venta: 'Venta', animales: 'Animales', sorteos: 'Sorteos', monto: 'Monto', animal_manual: 'Animal', agregar: 'Agregar jugada', emitir: 'Emitir ticket', selecciona: 'Selecciona al menos un animal y un sorteo.', selecciona_animal_y_sorteo: 'Selecciona al menos un animal y un sorteo antes de agregar la jugada.', selecciona_animal: 'Selecciona al menos un animal antes de agregar la jugada.', selecciona_sorteo: 'Selecciona al menos un sorteo antes de agregar la jugada.', animal_no_disponible: 'El animal ingresado no está disponible. Usa 00, 0 o un código entre 01 y 36.', animal_ya_seleccionado: 'El animal {{codigo}} ya está seleccionado.', agrega_jugada_antes_emitir: 'Agrega al menos una jugada antes de emitir el ticket.', accion_requiere_ticket: '{{accion}} requiere seleccionar un ticket desde el listado.', jugadas: 'Jugadas', total: 'Total', cupo: 'Cupo por animal', venta_exitosa: 'Ticket emitido', tema: 'Tema', claro: 'Claro', oscuro: 'Oscuro', idioma: 'Idioma', cancelar: 'Cancelar', ticket: 'Ticket', no_hay_jugadas: 'Aún no hay jugadas en el ticket.', limpiar_jugadas: 'Limpiar jugadas', monto_minimo: 'El monto mínimo es {{monto}}.', acceso_agencia: 'Acceso de Agencia', iniciar_descripcion: 'Ingresa con tus credenciales para registrar ventas.', error_sesion: 'No fue posible iniciar sesión.', disponible: 'Disponible', salir: 'Salir', todos: 'Todos', filtrar_sorteos: 'Filtrar sorteos', proximo_cierre: 'Cierra {{hora}} · {{sorteo}}', sin_sorteos_disponibles: 'Sin sorteos disponibles', menu: 'Menú', navegacion_principal: 'Navegación principal', venta_animalitos: 'Venta de animalitos', resumen_ventas: 'Resumen de ventas', ver_resultados: 'Ver resultados', listado_tickets: 'Listado de tickets', sesion_vencida: 'Tu sesión venció', sesion_vencida_descripcion: 'Volverás al inicio de sesión en unos segundos. También puedes salir ahora.', ...traduccionesConsulta.es } },
  it: { translation: { entrar: 'Accedi', usuario: 'Utente', contrasena: 'Password', cerrar_sesion: 'Esci', venta: 'Vendita', animales: 'Animali', sorteos: 'Estrazioni', monto: 'Importo', animal_manual: 'Animale', agregar: 'Aggiungi giocata', emitir: 'Emetti biglietto', selecciona: 'Seleziona almeno un animale e un’estrazione.', selecciona_animal_y_sorteo: 'Seleziona almeno un animale e un’estrazione prima di aggiungere la giocata.', selecciona_animal: 'Seleziona almeno un animale prima di aggiungere la giocata.', selecciona_sorteo: 'Seleziona almeno un’estrazione prima di aggiungere la giocata.', animal_no_disponible: 'L’animale inserito non è disponibile. Usa 00, 0 o un codice da 01 a 36.', animal_ya_seleccionado: 'L’animale {{codigo}} è già selezionato.', agrega_jugada_antes_emitir: 'Aggiungi almeno una giocata prima di emettere il biglietto.', accion_requiere_ticket: '{{accion}} richiede la selezione di un biglietto dall’elenco.', jugadas: 'Giocate', total: 'Totale', cupo: 'Limite per animale', venta_exitosa: 'Biglietto emesso', tema: 'Tema', claro: 'Chiaro', oscuro: 'Scuro', idioma: 'Lingua', cancelar: 'Annulla', ticket: 'Biglietto', no_hay_jugadas: 'Non ci sono ancora giocate nel biglietto.', limpiar_jugadas: 'Azzera giocate', monto_minimo: 'L’importo minimo è {{monto}}.', acceso_agencia: 'Accesso Agencia', iniciar_descripcion: 'Accedi per registrare le vendite.', error_sesion: 'Non è stato possibile accedere.', disponible: 'Disponibile', salir: 'Esci', todos: 'Tutti', filtrar_sorteos: 'Filtra estrazioni', proximo_cierre: 'Chiude alle {{hora}} · {{sorteo}}', sin_sorteos_disponibles: 'Nessuna estrazione disponibile', menu: 'Menu', navegacion_principal: 'Navigazione principale', venta_animalitos: 'Vendita di animaletti', resumen_ventas: 'Riepilogo vendite', ver_resultados: 'Vedi risultati', listado_tickets: 'Elenco biglietti', sesion_vencida: 'La sessione è scaduta', sesion_vencida_descripcion: 'Tornerai alla schermata di accesso tra pochi secondi. Puoi anche uscire subito.', ...traduccionesConsulta.it } },
};

const idiomaGuardado = localStorage.getItem('ag_idioma');
void i18n.use(initReactI18next).init({ resources: recursos, lng: idiomaGuardado ?? 'es', fallbackLng: 'es', interpolation: { escapeValue: false } });
export default i18n;
