import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ErrorApi, llamarApi } from '../../compartido/api/cliente';
import { formatearMonto as monto, fechaCaracas } from '../../compartido/utilidades/formato';
import type { Agencia, Catalogo, FormularioAgencia, Inicio, Vista } from './tipos';
import { formularioVacio } from './utilidades';

export function OperacionRuta({ token, alVencerSesion }: { token: string; alVencerSesion: () => void }) {
  const { t } = useTranslation(); const hoy = fechaCaracas();
  const [inicio, establecerInicio] = useState<Inicio | null>(null); const [vista, establecerVista] = useState<Vista>('agencias'); const [cargando, establecerCargando] = useState(true); const [mensaje, establecerMensaje] = useState('');
  const [desde, establecerDesde] = useState(hoy); const [hasta, establecerHasta] = useState(hoy); const [rangoAplicado, establecerRangoAplicado] = useState({ desde: hoy, hasta: hoy });
  const [modalResultado, establecerModalResultado] = useState(false); const [catalogo, establecerCatalogo] = useState<Catalogo | null>(null); const [fecha, establecerFecha] = useState(hoy); const [horario, establecerHorario] = useState(''); const [animal, establecerAnimal] = useState(''); const [guardando, establecerGuardando] = useState(false);
  const [modalAgencia, establecerModalAgencia] = useState(false); const [agenciaEditando, establecerAgenciaEditando] = useState<Agencia | null>(null); const [formularioAgencia, establecerFormularioAgencia] = useState<FormularioAgencia>(formularioVacio); const [guardandoAgencia, establecerGuardandoAgencia] = useState(false);
  useEffect(() => { if (!mensaje) return undefined; const temporizador = window.setTimeout(() => establecerMensaje(''), 3_000); return () => window.clearTimeout(temporizador); }, [mensaje]);
  const cargar = useCallback(async (rango = rangoAplicado) => { establecerCargando(true); try { establecerInicio(await llamarApi<Inicio>(`/operacion/inicio?${new URLSearchParams(rango).toString()}`, {}, token)); } catch (error) { if (error instanceof ErrorApi && error.estado === 401) alVencerSesion(); else establecerMensaje(error instanceof Error ? error.message : t('consulta_error')); } finally { establecerCargando(false); } }, [alVencerSesion, rangoAplicado, t, token]);
  useEffect(() => { void cargar(); }, [cargar]);
  const puedeAsignarGrupero = inicio?.perfil.tipo_usuario === 'BANQUERO';
  const titulo = inicio?.perfil.tipo_usuario === 'BANQUERO' ? t('panel_banquero') : t('panel_grupero');
  function buscarRango(evento: FormEvent) { evento.preventDefault(); if (desde > hasta) { establecerMensaje('La fecha inicial no puede ser posterior a la final.'); return; } const rango = { desde, hasta }; establecerRangoAplicado(rango); void cargar(rango); }
  async function abrirResultado() { try { const datos = await llamarApi<Catalogo>('/operacion/catalogo-resultados', {}, token); establecerCatalogo(datos); establecerHorario(datos.horarios[0] ? String(datos.horarios[0].pk_horario_sorteo) : ''); establecerAnimal(datos.animales[0] ? String(datos.animales[0].pk_animal) : ''); establecerModalResultado(true); } catch (error) { establecerMensaje(error instanceof Error ? error.message : t('consulta_error')); } }
  async function guardarResultado(evento: FormEvent) { evento.preventDefault(); if (!fecha || !horario || !animal) { establecerMensaje(t('resultado_incompleto')); return; } establecerGuardando(true); try { const respuesta = await llamarApi<{ mensaje: string }>('/operacion/resultados', { method: 'POST', body: JSON.stringify({ fecha_juego: fecha, fk_horario_sorteo: Number(horario), fk_animal: Number(animal) }) }, token); establecerMensaje(respuesta.mensaje); establecerModalResultado(false); await cargar(); } catch (error) { establecerMensaje(error instanceof Error ? error.message : t('consulta_error')); } finally { establecerGuardando(false); } }
  async function liberarEquipo(pkAgencia: string) { try { const respuesta = await llamarApi<{ mensaje: string }>(`/operacion/agencias/${pkAgencia}/liberar-serial`, { method: 'POST' }, token); establecerMensaje(respuesta.mensaje); await cargar(); } catch (error) { establecerMensaje(error instanceof Error ? error.message : t('consulta_error')); } }
  function abrirAgencia(agencia?: Agencia) { establecerAgenciaEditando(agencia ?? null); establecerFormularioAgencia(agencia ? { codigo_agencia: agencia.codigo_agencia, nombre_agencia: agencia.nombre_agencia, nombre_usuario: agencia.operador, contrasena: '', comision_porcentaje: agencia.comision_porcentaje ?? '12', cupo_animal: agencia.cupo_animal ?? '100', jugada_minima: agencia.jugada_minima ?? '1', minutos_cierre: String(agencia.minutos_cierre ?? 5), fk_grupero: agencia.grupero ?? '', activa: agencia.activa } : formularioVacio()); establecerModalAgencia(true); }
  function cambiarCampo(campo: keyof FormularioAgencia, valor: string | boolean) { establecerFormularioAgencia((actual) => ({ ...actual, [campo]: valor })); }
  async function guardarAgencia(evento: FormEvent) { evento.preventDefault(); const datos = { nombre_agencia: formularioAgencia.nombre_agencia, comision_porcentaje: Number(formularioAgencia.comision_porcentaje), cupo_animal: Number(formularioAgencia.cupo_animal), jugada_minima: Number(formularioAgencia.jugada_minima), minutos_cierre: Number(formularioAgencia.minutos_cierre), activa: formularioAgencia.activa, ...(puedeAsignarGrupero ? { fk_grupero: formularioAgencia.fk_grupero || undefined } : {}) }; if (!agenciaEditando && (!formularioAgencia.codigo_agencia || !formularioAgencia.nombre_usuario || !formularioAgencia.contrasena)) { establecerMensaje('Completa código, usuario y contraseña para crear la agencia.'); return; } establecerGuardandoAgencia(true); try { const respuesta = await llamarApi<{ mensaje: string }>(agenciaEditando ? `/operacion/agencias/${agenciaEditando.pk_agencia}` : '/operacion/agencias', { method: agenciaEditando ? 'PATCH' : 'POST', body: JSON.stringify(agenciaEditando ? datos : { ...datos, codigo_agencia: formularioAgencia.codigo_agencia, nombre_usuario: formularioAgencia.nombre_usuario, contrasena: formularioAgencia.contrasena }) }, token); establecerMensaje(respuesta.mensaje); establecerModalAgencia(false); await cargar(); } catch (error) { establecerMensaje(error instanceof Error ? error.message : t('consulta_error')); } finally { establecerGuardandoAgencia(false); } }
  async function desactivarAgencia(agencia: Agencia) { if (!window.confirm(`¿Desactivar ${agencia.nombre_agencia}? Se conserva todo su historial.`)) return; try { const respuesta = await llamarApi<{ mensaje: string }>(`/operacion/agencias/${agencia.pk_agencia}`, { method: 'DELETE' }, token); establecerMensaje(respuesta.mensaje); await cargar(); } catch (error) { establecerMensaje(error instanceof Error ? error.message : t('consulta_error')); } }
  if (cargando && !inicio) return <p className="estado-pagina">{t('cargando')}</p>; if (!inicio) return <p className="estado-pagina mensaje-error">{mensaje || t('consulta_error')}</p>;
  return <section className="operacion"><header className="encabezado-operacion"><div><h1>{titulo}</h1><p>{inicio.perfil.nombre_completo}</p></div><span>{inicio.resumen.agencias} {t('agencias')}</span></header><form className="filtros-rango filtros-operacion" onSubmit={buscarRango}><label>{t('desde')}<input type="date" value={desde} onChange={(evento) => establecerDesde(evento.target.value)} required /></label><label>{t('hasta')}<input type="date" value={hasta} onChange={(evento) => establecerHasta(evento.target.value)} required /></label><button className="boton-secundario" disabled={cargando}>{cargando ? 'Actualizando…' : t('buscar')}</button></form><section className="metricas-operacion" aria-label={t('resumen_ventas')}><div><span>{t('total_vendido')}</span><strong>{monto(inicio.resumen.total_vendido)}</strong></div><div><span>{t('total_premiado')}</span><strong>{monto(inicio.resumen.total_premiado)}</strong></div><div><span>{t('tickets')}</span><strong>{inicio.resumen.tickets}</strong></div><div><span>{t('agencias')}</span><strong>{inicio.resumen.agencias}</strong></div></section><nav className="pestanas-operacion" aria-label={t('navegacion_principal')}><button type="button" className={vista === 'agencias' ? 'activo' : ''} onClick={() => establecerVista('agencias')}>{t('agencias')}</button><button type="button" className={vista === 'tickets' ? 'activo' : ''} onClick={() => establecerVista('tickets')}>{t('listado_tickets')}</button><button type="button" className={vista === 'resultados' ? 'activo' : ''} onClick={() => establecerVista('resultados')}>{t('ver_resultados')}</button></nav>
    {vista === 'agencias' && <div className="tablero-operacion">{inicio.perfil.tipo_usuario === 'BANQUERO' && <section className="tarjeta bloque-operacion"><h2>{t('gruperos')}</h2>{inicio.gruperos.length ? <div className="lista-operacion">{inicio.gruperos.map((grupero) => <div key={grupero.pk_grupero}><strong>{grupero.nombre_completo}</strong><span className={grupero.activo ? 'estado-activo' : 'estado-inactivo'}>{grupero.activo ? t('activo') : t('inactivo')}</span></div>)}</div> : <p className="vacio-operacion">{t('sin_gruperos')}</p>}</section>}<section className="tarjeta bloque-operacion agencias-admin"><header className="cabecera-bloque"><h2>{t('agencias')}</h2><button type="button" className="boton-primario" onClick={() => abrirAgencia()}>Crear agencia</button></header>{inicio.agencias.length ? <div className="tabla-operacion">{inicio.agencias.map((agencia) => <div key={agencia.pk_agencia}><span><strong>{agencia.nombre_agencia}</strong><small>{agencia.codigo_agencia} · {agencia.operador} · {agencia.equipo_asignado ? t('equipo_asignado') : t('sin_equipo')}</small></span><span className={agencia.activa ? 'estado-activo' : 'estado-inactivo'}>{agencia.activa ? t('activo') : t('inactivo')}</span><div className="acciones-fila"><button type="button" className="boton-secundario" onClick={() => abrirAgencia(agencia)}>Editar</button>{agencia.equipo_asignado && <button type="button" className="boton-secundario" onClick={() => void liberarEquipo(agencia.pk_agencia)}>{t('liberar_equipo')}</button>}{agencia.activa && <button type="button" className="boton-peligro" onClick={() => void desactivarAgencia(agencia)}>Desactivar</button>}</div></div>)}</div> : <p className="vacio-operacion">{t('sin_agencias')}</p>}</section></div>}
    {vista === 'tickets' && <section className="tarjeta bloque-operacion"><h2>{t('listado_tickets')}</h2>{inicio.tickets.length ? <div className="tabla-operacion">{inicio.tickets.map((ticket) => <div key={ticket.serial}><span><strong>#{ticket.numero_ticket} · {ticket.agencia}</strong><small>{ticket.fecha_juego} · {ticket.serial}</small></span><span className={`estado-ticket ${ticket.estado.toLowerCase()}`}>{ticket.estado}</span><strong>{monto(ticket.total_jugado)}</strong></div>)}</div> : <p className="vacio-operacion">{t('sin_tickets')}</p>}</section>}
    {vista === 'resultados' && <section className="tarjeta bloque-operacion"><header className="cabecera-bloque"><h2>{t('ver_resultados')}</h2>{inicio.permisos.puede_registrar_resultados && <button type="button" className="boton-primario" onClick={() => void abrirResultado()}>{t('registrar_resultado')}</button>}</header>{inicio.resultados.length ? <div className="tabla-operacion">{inicio.resultados.map((resultado) => <div key={resultado.pk_resultado}><span><strong>{resultado.sorteo} · {resultado.hora}</strong><small>{resultado.fecha_juego}</small></span><strong>{resultado.icono_animal} {resultado.codigo_animal} · {resultado.nombre_animal}</strong></div>)}</div> : <p className="vacio-operacion">{t('sin_resultados')}</p>}</section>}
    {mensaje && <p className="notificacion emergente" role="status">{mensaje}</p>}
    {modalResultado && <div className="fondo-consulta"><form className="ventana-consulta tarjeta formulario-resultado" onSubmit={guardarResultado}><header className="encabezado-consulta"><h2>{t('registrar_resultado')}</h2><button type="button" className="boton-cerrar" aria-label={t('cerrar')} onClick={() => establecerModalResultado(false)}>×</button></header><label>{t('fecha')}<input type="date" value={fecha} onChange={(evento) => establecerFecha(evento.target.value)} required /></label><label>{t('sorteos')}<select value={horario} onChange={(evento) => establecerHorario(evento.target.value)} required>{catalogo?.horarios.map((item) => <option key={item.pk_horario_sorteo} value={item.pk_horario_sorteo}>{item.sorteo} · {item.hora}</option>)}</select></label><label>{t('animal_manual')}<select value={animal} onChange={(evento) => establecerAnimal(evento.target.value)} required>{catalogo?.animales.map((item) => <option key={item.pk_animal} value={item.pk_animal}>{item.icono} {item.codigo_animal} · {item.nombre}</option>)}</select></label><button className="boton-primario" disabled={guardando}>{guardando ? '…' : t('guardar_resultado')}</button></form></div>}
    {modalAgencia && <div className="fondo-consulta"><form className="ventana-consulta tarjeta formulario-agencia" onSubmit={guardarAgencia}><header className="encabezado-consulta"><h2>{agenciaEditando ? 'Editar agencia' : 'Crear agencia'}</h2><button type="button" className="boton-cerrar" aria-label={t('cerrar')} onClick={() => establecerModalAgencia(false)}>×</button></header><div className="campos-agencia">{!agenciaEditando && <><label>Código de agencia<input value={formularioAgencia.codigo_agencia} onChange={(evento) => cambiarCampo('codigo_agencia', evento.target.value.toUpperCase())} placeholder="AG-002" required /></label><label>Usuario de acceso<input value={formularioAgencia.nombre_usuario} onChange={(evento) => cambiarCampo('nombre_usuario', evento.target.value)} autoComplete="username" required /></label><label>Contraseña inicial<input type="password" value={formularioAgencia.contrasena} onChange={(evento) => cambiarCampo('contrasena', evento.target.value)} autoComplete="new-password" minLength={6} required /></label></>}<label>Nombre de la agencia<input value={formularioAgencia.nombre_agencia} onChange={(evento) => cambiarCampo('nombre_agencia', evento.target.value)} required /></label><label>Comisión (%)<input type="number" min="0" max="100" step=".001" value={formularioAgencia.comision_porcentaje} onChange={(evento) => cambiarCampo('comision_porcentaje', evento.target.value)} required /></label><label>Cupo por animal<input type="number" min="1" step=".01" value={formularioAgencia.cupo_animal} onChange={(evento) => cambiarCampo('cupo_animal', evento.target.value)} required /></label><label>Jugada mínima<input type="number" min="1" step=".01" value={formularioAgencia.jugada_minima} onChange={(evento) => cambiarCampo('jugada_minima', evento.target.value)} required /></label><label>Minutos de cierre<input type="number" min="0" max="120" value={formularioAgencia.minutos_cierre} onChange={(evento) => cambiarCampo('minutos_cierre', evento.target.value)} required /></label>{puedeAsignarGrupero && <label>Grupero<select value={formularioAgencia.fk_grupero} onChange={(evento) => cambiarCampo('fk_grupero', evento.target.value)}><option value="">Sin grupero asignado</option>{inicio.gruperos.filter((grupero) => grupero.activo).map((grupero) => <option key={grupero.pk_grupero} value={grupero.pk_grupero}>{grupero.nombre_completo}</option>)}</select></label>}{agenciaEditando && <label className="campo-check"><input type="checkbox" checked={formularioAgencia.activa} onChange={(evento) => cambiarCampo('activa', evento.target.checked)} /> Agencia activa</label>}</div><div className="acciones-modal"><button type="button" className="boton-secundario" onClick={() => establecerModalAgencia(false)}>{t('cancelar')}</button><button className="boton-primario" disabled={guardandoAgencia}>{guardandoAgencia ? 'Guardando…' : agenciaEditando ? 'Guardar cambios' : 'Crear agencia'}</button></div></form></div>}
  </section>;
}
